Improvments
Regikul/rebar3_ospkg pull request #1
Opened 2017-12-04 12:33 UTC by NoobsEnslaver

2017-12-04 16:37 UTC, Regikul requested changes

2017-12-04 16:37 UTC, Regikul commented on README.md
> +    {fakeroot, "/opt"}
Давай только не `fakeroot`, а `install_dir`. И не в `ospkg.deb`, а на уровень выше, в `ospkg`, потому что тут нет специфики для deb-пакетов.

Алсо, загляни в функу `generate_md5sums_file`, она предполагает наличие `/opt/`, а с этим PR должна смотреть на указанную в конфиге директорию.

2017-12-04 16:37 UTC, Regikul commented on src/rebar3_ospkg_prv.erl
> +                    case lists:keyfind(fakeroot, 1, Options) of
Нет кейса - нет проблемы. :) Это я переносе `fakeroot` на уровень выше.

2017-12-05 10:59 UTC, Regikul requested changes

2017-12-05 10:59 UTC, Regikul commented on src/rebar3_ospkg_prv.erl
> +  FakeRootDir = case lists:keyfind(install_dir, 1, rebar_state:get(State, ospkg, [])) of
Клево, так лучше. Но `generate_md5sums_file/2` все ещё не смотрит в конфиг и считает что мы всегда устанавливаем пакет в `/opt/`, без того патч будет считать md5 неправильно.

2017-12-07 09:31 UTC, NoobsEnslaver commented on src/rebar3_ospkg_prv.erl
> +  FakeRootDir = case lists:keyfind(install_dir, 1, rebar_state:get(State, ospkg, [])) of
fixed

2017-12-11 08:22 UTC, Regikul approved these changes

2017-12-11 08:22 UTC, merged